version: '3.8'

services:
  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    container_name: firefly_importer
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .importer.env
    volumes:
      - ./import:/import
      - ./configurations:/configurations
    networks:
      - firefly_network
    extra_hosts:
      # Allow container to reach host services
      - "host.docker.internal:host-gateway"

networks:
  firefly_network:
    driver: bridge
